[package]
name = "keys_from_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
pgp = "0.9.0"
rand = "0.8.5"
